using System.Text;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SistemaAlmacen.Core.Entidades;
using SistemaAlmacen.Infrastructure;

// Cargar variables de entorno desde el archivo .env si existe en el directorio de trabajo o padres
var currentDir = Directory.GetCurrentDirectory();
while (!string.IsNullOrEmpty(currentDir))
{
    var envPath = Path.Combine(currentDir, ".env");
    if (File.Exists(envPath))
    {
        foreach (var line in File.ReadAllLines(envPath))
        {
            if (string.IsNullOrWhiteSpace(line) || line.StartsWith("#")) continue;
            var parts = line.Split('=', 2);
            if (parts.Length == 2)
            {
                var key = parts[0].Trim();
                var val = parts[1].Trim();
                if (val.StartsWith("\"") && val.EndsWith("\"") && val.Length >= 2)
                {
                    val = val[1..^1];
                }
                Environment.SetEnvironmentVariable(key, val);
            }
        }
        break;
    }
    currentDir = Directory.GetParent(currentDir)?.FullName;
}

var builder = WebApplication.CreateBuilder(args);

// Enums como texto en JSON (el frontend envía/recibe "Admin", "Entrada", etc.)
builder.Services.AddControllers().AddJsonOptions(o =>
    o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

builder.Services.AddDbContext<AppDbContext>(o =>
{
    var connectionString = Environment.GetEnvironmentVariable("DATABASE_URL")
        ?? builder.Configuration.GetConnectionString("Default");
    o.UseNpgsql(connectionString, npgsqlOptions =>
    {
        npgsqlOptions.EnableRetryOnFailure(
            maxRetryCount: 5,
            maxRetryDelay: TimeSpan.FromSeconds(30),
            errorCodesToAdd: null);
    });
});

builder.Services.AddScoped<MovimientoService>();

var jwtSection = builder.Configuration.GetSection("Jwt");
var jwtKey = Environment.GetEnvironmentVariable("JWT_KEY")
             ?? jwtSection["Key"]
             ?? "clave-desarrollo-cambiar-en-produccion-minimo-32-chars";

if (jwtKey == "clave-desarrollo-cambiar-en-produccion-minimo-32-chars")
{
    jwtKey = "ProduccionClaveSeguraSistemaAlmacenOvoPlus2026_987654321_Key";
}

var jwtIssuer = jwtSection["Issuer"] ?? "SistemaAlmacen";
var jwtExpiraMinutos = int.TryParse(jwtSection["ExpiraMinutos"], out var min) ? min : 480;

var adminPass = Environment.GetEnvironmentVariable("SEED_ADMIN_PASSWORD")
                ?? builder.Configuration["Seed:AdminPassword"]
                ?? "Admin123!";

var envAllowedOrigins = Environment.GetEnvironmentVariable("CORS_ALLOWED_ORIGINS");
var origenesPermitidos = !string.IsNullOrEmpty(envAllowedOrigins)
    ? envAllowedOrigins.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
    : builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];

builder.Services.AddSingleton(new TokenService(jwtKey, jwtIssuer, jwtExpiraMinutos));

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(o => o.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtIssuer,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
    });
builder.Services.AddAuthorization();

builder.Services.AddCors(o => o.AddDefaultPolicy(p =>
{
    if (origenesPermitidos.Length > 0 && !origenesPermitidos.Contains("*"))
    {
        p.WithOrigins(origenesPermitidos).AllowAnyHeader().AllowAnyMethod();
    }
    else
    {
        p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod();
    }
}));

var app = builder.Build();

// Seed: primer usuario admin si la tabla está vacía.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    db.Database.Migrate();
    try
    {
        db.Database.ExecuteSqlRaw("ALTER TABLE \"Productos\" ADD COLUMN IF NOT EXISTS \"ImagenUrl\" TEXT;");
        db.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""TareasLogistica"" (
                ""Id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Titulo"" TEXT NOT NULL,
                ""Descripcion"" TEXT NULL,
                ""ChoferId"" INT NOT NULL REFERENCES ""Usuarios""(""Id"") ON DELETE RESTRICT,
                ""AlmacenOrigenId"" INT NULL REFERENCES ""Almacenes""(""Id"") ON DELETE RESTRICT,
                ""AlmacenDestinoId"" INT NULL REFERENCES ""Almacenes""(""Id"") ON DELETE RESTRICT,
                ""Estado"" INT NOT NULL DEFAULT 1,
                ""FechaAsignacion"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                ""FechaCompletado"" TIMESTAMP WITH TIME ZONE NULL,
                ""NotasChofer"" TEXT NULL
            );
        ");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error initializing DB tables: {ex.Message}");
    }
    if (!db.Usuarios.Any())
    {
        db.Usuarios.Add(new Usuario
        {
            Email = "admin@almacen.local",
            Nombre = "Administrador",
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(
                builder.Configuration["Seed:AdminPassword"] ?? "Admin123!"),
            Rol = Rol.Admin,
        });
        db.SaveChanges();
    }
}

app.UseMiddleware<SistemaAlmacen.Api.ManejadorErrores>();
app.UseStaticFiles();
app.UseCors();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.Run();

// Necesario para WebApplicationFactory<Program> en los tests de integración
// (top-level statements generan una clase Program interna por defecto).
public partial class Program { }
